### ISSUE TITLE
Change Text Under Project & Training Section

### ISSUE THREAD

**Issue by naumanarif21** [Subhodeep-Karmakar/Digital-Resume#1]
"I am a trainee at Nullstack Technologies Pvt. Ltd. & during this training my subjects are Python, Html, CSS, JAVA scripts, Django."

Change -> 
**Subject** to **Language/Technologies**
**JAVA scripts** > **JavaScript**
@Subhodeep-Karmakar

**Comment by Subhodeep-Karmakar** [comment]
issue have been resolved
